version: '3'
services:
  db:
    image: mysql:5.7
    container_name: judger-db
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./docker/db/init:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    expose:
      - "3306"
  app:
    image: szfck/judger-php
    container_name: judger-app
    command: bash -c "service apache2 restart && tail -f /dev/null"
    volumes:
      - .:/var/www/html
    ports: 
      - ${PORT}:80
    depends_on:
      - db
  judge:
    container_name: judger-judge
    build: ./docker/judge
    restart: always
    volumes:
      - .:/judge
    depends_on:
      - db
    ports:
      - 3000:3000
    command: sh -c "cd docker/judge && FLASK_DEBUG=1 python app.py"
    environment:
      - PYTHONUNBUFFERED=1
